WMS 11287: Request to publish "Simplify User Management by Integrating Oracle Autonomous Database and Oracle Cloud Identity" LiveLab
oracle-livelabs/database pull request #153
Opened 2023-01-26 21:18 UTC by milesnov

WMS 11287

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-01-27 19:32 UTC, NGalloso submitted a review, later dismissed

2023-01-27 23:54 UTC, william-masdon-oracle requested changes
please rename your files and folders to adhere to the standard in the Self QA document. Instead of lab_1-setup-environment.md it should just be setup-environment.md

2023-01-30 14:28 UTC, milesnov commented
The file and folder names have been updated to fit the standard.

2023-01-30 22:05 UTC, kamryn-v approved these changes

2023-01-30 22:05 UTC, kamryn-v approved these changes

2023-01-30 22:07 UTC, merged