Changes and improvements following initial review.
oracle-livelabs/database pull request #22
Opened 2022-07-05 14:28 UTC by ChrisJ60

Probably one more pull request to follow this one once the image is live in marketplace. I want to merge these now as this should then be virtually the final version and it can go for another round of review.

2022-07-05 15:31 UTC, klazarz requested changes
Hi @ChrisJ60 please update the URLs in in all index.html and manifest.json files (all located in the workshops folder):
1. https://oracle.github.io/learning-library/common/ needs to be changed to https://oracle-livelabs.github.io/common/
2. https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/ needs to be changed to https://oracle-livelabs.github.io/common/
3. https://bit.ly/golivelabs needs to be changed to https://developer.oracle.com/livelabs

Thanks a lot,
Kevin

2022-07-05 15:49 UTC, ChrisJ60 commented
Done and pushed to GitHub. Do I need to initiate a new pull request?

Chris


From: Kevin Lazarz ***@***.***>
Reply to: oracle-livelabs/database ***@***.***>
Date: Tuesday, 5 July 2022 at 16:31
To: oracle-livelabs/database ***@***.***>
Cc: Chris Jenkins ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/database] Changes and improvements following initial review. (PR #22)


@klazarz requested changes on this pull request.

Hi @ChrisJ60<https://urldefense.com/v3/__https:/github.com/ChrisJ60__;!!ACWV5N9M2RV99hQ!IZ4VzE94FEQsgQKWQrWwJ-l9TYVqtyuUDnutyKTpSsteSvTMUMI0VbPo_Iuf3qRxBth3jsB3D04DP6PjA2TcJEd9hyY$> please update the URLs in in all index.html and manifest.json files (all located in the workshops folder):
1.       https://oracle.github.io/learning-library/common/<https://urldefense.com/v3/__https:/oracle.github.io/learning-library/common/__;!!ACWV5N9M2RV99hQ!IZ4VzE94FEQsgQKWQrWwJ-l9TYVqtyuUDnutyKTpSsteSvTMUMI0VbPo_Iuf3qRxBth3jsB3D04DP6PjA2Tc2JNiPj8$> needs to be changed to https://oracle-livelabs.github.io/common/<https://urldefense.com/v3/__https:/oracle-livelabs.github.io/common/__;!!ACWV5N9M2RV99hQ!IZ4VzE94FEQsgQKWQrWwJ-l9TYVqtyuUDnutyKTpSsteSvTMUMI0VbPo_Iuf3qRxBth3jsB3D04DP6PjA2Tc-MSwnFk$>
2.       https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/ needs to be changed to https://oracle-livelabs.github.io/common/<https://urldefense.com/v3/__https:/oracle-livelabs.github.io/common/__;!!ACWV5N9M2RV99hQ!IZ4VzE94FEQsgQKWQrWwJ-l9TYVqtyuUDnutyKTpSsteSvTMUMI0VbPo_Iuf3qRxBth3jsB3D04DP6PjA2Tc-MSwnFk$>
3.       https://bit.ly/golivelabs<https://urldefense.com/v3/__https:/bit.ly/golivelabs__;!!ACWV5N9M2RV99hQ!IZ4VzE94FEQsgQKWQrWwJ-l9TYVqtyuUDnutyKTpSsteSvTMUMI0VbPo_Iuf3qRxBth3jsB3D04DP6PjA2TclnT2IDY$> needs to be changed to https://developer.oracle.com/livelabs

Thanks a lot,
Kevin

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/database/pull/22*pullrequestreview-1028833017__;Iw!!ACWV5N9M2RV99hQ!IZ4VzE94FEQsgQKWQrWwJ-l9TYVqtyuUDnutyKTpSsteSvTMUMI0VbPo_Iuf3qRxBth3jsB3D04DP6PjA2Tc2jc6DQE$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AAVGVFSMXL6NWBCHNYCVK5DVSRIODANCNFSM52WNQSHQ__;!!ACWV5N9M2RV99hQ!IZ4VzE94FEQsgQKWQrWwJ-l9TYVqtyuUDnutyKTpSsteSvTMUMI0VbPo_Iuf3qRxBth3jsB3D04DP6PjA2TciKKIFu8$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-06 11:37 UTC, klazarz approved these changes

2022-07-06 12:25 UTC, klazarz approved these changes

2022-07-06 12:25 UTC, merged