WMS: 11287 Quarterly QA Update
oracle-livelabs/database pull request #248
Opened 2023-04-28 17:58 UTC by milesnov

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-04-28 20:33 UTC, ramumg requested changes
Hi @milesnov, 

Please make sure that you go over the QA document.
[QA (6).docx](https://github.com/oracle-livelabs/database/files/11357130/QA.6.docx)

The introduction page doesn't follow the livelabs format. 

Let me know if you have any question. 

Thank you, 
Ramu

2023-05-01 13:43 UTC, milesnov commented
Hi,

I just updated the introduction format and pushed the changes. Let me know if anything else needs to be updated.

Thanks,
Miles

From: ramumg ***@***.***>
Date: Friday, April 28, 2023 at 3:34 PM
To: oracle-livelabs/database ***@***.***>
Cc: Miles Novotny ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/database] WMS: 11287 Quarterly QA Update (PR #248)

@ramumg requested changes on this pull request.

Hi @milesnov<https://urldefense.com/v3/__https:/github.com/milesnov__;!!ACWV5N9M2RV99hQ!Pt3jorZ5Dylilv4-_Ixxnjap7oChBtltlEMUBioBSbFA7HETd6JOxgQ39KnLIHzUwk30htYO22xkoN453K6Aztdgx0ww$>,

Please make sure that you go over the QA document.
QA (6).docx<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/database/files/11357130/QA.6.docx__;!!ACWV5N9M2RV99hQ!Pt3jorZ5Dylilv4-_Ixxnjap7oChBtltlEMUBioBSbFA7HETd6JOxgQ39KnLIHzUwk30htYO22xkoN453K6Azog1p7xo$>

The introduction page doesn't follow the livelabs format.

Let me know if you have any question.

Thank you,
Ramu

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/database/pull/248*pullrequestreview-1406573058__;Iw!!ACWV5N9M2RV99hQ!Pt3jorZ5Dylilv4-_Ixxnjap7oChBtltlEMUBioBSbFA7HETd6JOxgQ39KnLIHzUwk30htYO22xkoN453K6AzmKTz1Zu$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/A2B6UGRSGGO5MNOS3E2W73LXDQSUDANCNFSM6AAAAAAXPRFJSU__;!!ACWV5N9M2RV99hQ!Pt3jorZ5Dylilv4-_Ixxnjap7oChBtltlEMUBioBSbFA7HETd6JOxgQ39KnLIHzUwk30htYO22xkoN453K6AzoXPtHN_$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-01 14:53 UTC, rahul-tasker approved these changes

2023-05-01 15:03 UTC, ramumg approved these changes

2023-05-01 15:04 UTC, merged