WMS ID  11453: new LiveLab for Data Sovereignty with user-defined sharding of Oracle Globally Distributed Database 19c
oracle-livelabs/database pull request #418
Opened 2023-10-03 21:47 UTC by OraGitPush1

# WMS ID 11453

# General requirements
1. Information in the workshop is adequate and updated
WMS ID  11453: new LiveLab for Data Sovereignty with user-defined sharding of Oracle Globally Distributed Database 19c
3. Code is correct and working : yes
4. Links are correct: yes
5. Make sure you enter the help email link in your manifest.json: yes
6. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

2023-10-04 14:15 UTC, denisemyrick requested changes

2023-10-04 14:15 UTC, denisemyrick commented on sharding/uds19c/cleanup/uds19c-cleanup.md
Task 1 step 4 - need a space after the period.

2023-10-05 00:39 UTC, OraGitPush1 commented on sharding/uds19c/cleanup/uds19c-cleanup.md
done. ready for review

2023-10-05 00:40 UTC, OraGitPush1 commented on sharding/uds19c/cleanup/uds19c-cleanup.md
done. ready for review.

2023-10-05 23:35 UTC, anooshapilli approved these changes

2023-10-05 23:35 UTC, merged